[package]
name = "scryfall-sdk-rust"
version = "0.1.0"
edition = "2021"

[features]
full = ["blocking"]
blocking = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.10", features = ["json", "blocking"]}
serde = { version = "1.0.137", features = ["derive"]}
serde_json = "1.0.81"

[dev-dependencies]
httpmock = "0.6"
tokio = {version = "1.19.2", features = ["macros", "tokio-macros"]}
